services:

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: manoel
      POSTGRES_PASSWORD: Manoel!123
      POSTGRES_DB: desafio_anlix
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vehicle

  backend:
    image: manoelpiovesan/desafioanlix-back:latest
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/desafio_anlix
      QUARKUS_DATASOURCE_USERNAME: manoel
      QUARKUS_DATASOURCE_PASSWORD: Manoel!123
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - vehicle


networks:
  vehicle:
    name: quarkus-vehicle-network
    driver: bridge