name: desafio_anlix_front_folly_fields
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  agattp:
    git:
      url: git@github.com:anlix-io/agattp.git
      ref: main

  chart_sparkline: ^1.0.15+1
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  # https://pub.dev/packages/folly_fields
  folly_fields: ^2.6.1




dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
